config:
    AZURE_SUBSCRIPTION_ID: "xxxx" # Please modify to your subscription
    AZURE_RESOURCE_GROUP: "xxxx" # Please modify to your Azure resource group
    AZURE_WORKSPACE: "xxxx" # Please modify to your Azure workspace
    HF_TOKEN: "xxxx" # Please modify to your Hugging Face token
    HF_MODEL_NAME_OR_PATH: "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
    IS_DEBUG: true

serve:
    azure_env_name: "llm-serving-vllm-2025-01-28" # Please modify to your AzureML env name
    azure_model_name: "deepseek-r1-distill-v1" # Please modify to your AzureML model name
    azure_endpoint_name: "deepseek-r1-endpoint-v1"
    azure_deployment_name: "deepseek-r1-distill-blue"
    azure_serving_cluster_size: "Standard_NC24ads_A100_v4" # 1 x A100 (80GB)